Biblioteka <span style="color:red;font-size:16pt;font-weight:bold">NUMPY</span> - podstawowe funkcje
<p>
<img src="supernova.jpg" width=300>
</p>

In [1]:
import numpy as np

In [2]:
k = np.linspace(0,10,num=5)
k

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [14]:
nb = [45,89,2,-4,16,-33,0,135,567,-222,15,8,9,12,-20,11]
nnb = np.array(nb)
print(nnb)

[  45   89    2   -4   16  -33    0  135  567 -222   15    8    9   12
  -20   11]


In [15]:
sorted(nnb)

[-222, -33, -20, -4, 0, 2, 8, 9, 11, 12, 15, 16, 45, 89, 135, 567]

In [16]:
nnb_x = nnb.copy()

In [17]:
nnb.sort()

In [18]:
nnb

array([-222, -33, -20, -4, 0, 2, 8, 9, 11, 12, 15,
 16, 45, 89, 135, 567])

In [19]:
nnb_x

array([ 45, 89, 2, -4, 16, -33, 0, 135, 567, -222, 15,
 8, 9, 12, -20, 11])

In [21]:
a = np.array([1,5,8,11])
b = np.array([2,5,9,13])
c = np.array([56,99])

big = np.concatenate((a,b,c))
big

array([ 1, 5, 8, 11, 2, 5, 9, 13, 56, 99])

In [23]:
#macierze
x = np.array([[3,4],[19,6]])
x

array([[ 3, 4],
 [19, 6]])

In [24]:
y = np.array([[7,11],[45,2]])
y

array([[ 7, 11],
 [45, 2]])

In [27]:
p = np.concatenate((x,y),axis=0)
p

array([[ 3, 4],
 [19, 6],
 [ 7, 11],
 [45, 2]])

In [29]:
p[1][0]

19

In [30]:
p[1,0]

19

In [32]:
lg = [[4,5,3,2],[5,7,23,42]]
lg

[[4, 5, 3, 2], [5, 7, 23, 42]]

In [34]:
lg[0][1]

5

In [36]:
pr = np.arange(12)
pr

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [40]:
pp = pr.reshape(4,3)
pp

array([[ 0, 1, 2],
 [ 3, 4, 5],
 [ 6, 7, 8],
 [ 9, 10, 11]])

In [41]:
#warunkowe przeszukiwanie macierzy

w = np.array([[1,2,3,4],[99,34,56,77],[21,33,14,15]])
w

array([[ 1, 2, 3, 4],
 [99, 34, 56, 77],
 [21, 33, 14, 15]])

In [42]:
w[w<5]

array([1, 2, 3, 4])

In [44]:
pv = (w%2==0)
pv

array([[False, True, False, True],
 [False, True, True, False],
 [False, False, True, False]])

In [45]:
w[pv]

array([ 2, 4, 34, 56, 14])

In [47]:
c = w[(w>2)&(w<=21)]
c

array([ 3, 4, 21, 14, 15])

In [48]:
v = w[(w<=8)|(w>50)]
v

array([ 1, 2, 3, 4, 99, 56, 77])

In [49]:
#operacje na wekorach
dane = np.array([1,3,8])
ones = np.ones(3,dtype=int)
tw = np.array([2,2,3])

In [50]:
dane+ones

array([2, 4, 9])

In [51]:
dane-ones

array([0, 2, 7])

In [52]:
dane*tw

array([ 2, 6, 24])

In [53]:
dane/tw

array([0.5 , 1.5 , 2.66666667])

In [54]:
dane*2.33

array([ 2.33, 6.99, 18.64])

In [55]:
tab = np.array([[1,6],[27,19]])
tab

array([[ 1, 6],
 [27, 19]])

In [56]:
tab.sum(axis=0)

array([28, 25])

In [57]:
tab.sum(axis=1)

array([ 7, 46])

In [58]:
tab.max()

27

In [59]:
tab.min()

1

In [60]:
tab.mean()

13.25

In [61]:
tab.std()

10.304731922762475