In [1]:
import pandas as pd

In [2]:
obj = pd.Series([4,7,-5,3])
obj

0 4
1 7
2 -5
3 3
dtype: int64

In [3]:
type(obj)

pandas.core.series.Series

In [4]:
obj.values

array([ 4, 7, -5, 3])

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4,7,-5,3],index=['a','b','d','c'])
obj2

a 4
b 7
d -5
c 3
dtype: int64

In [7]:
obj2['a']

4

In [8]:
obj2['d'] = 888
obj2

a 4
b 7
d 888
c 3
dtype: int64

In [9]:
obj2['g'] = 100
obj2

a 4
b 7
d 888
c 3
g 100
dtype: int64

In [10]:
obj2[['c','d']]

c 3
d 888
dtype: int64

In [11]:
obj2[obj2>6]

b 7
d 888
g 100
dtype: int64

In [12]:
obj2*2

a 8
b 14
d 1776
c 6
g 200
dtype: int64

In [13]:
'b' in obj2

True

In [14]:
'h' in obj2

False

In [15]:
s = {'Warszawa':45678,'Kraków':44323,'Lublin':41988,'Gdańsk':40122}
s

{'Warszawa': 45678, 'Kraków': 44323, 'Lublin': 41988, 'Gdańsk': 40122}

In [16]:
obj3 = pd.Series(s)
obj3

Warszawa 45678
Kraków 44323
Lublin 41988
Gdańsk 40122
dtype: int64

In [17]:
miasta = ['Poznań','Kraków','Rzeszów','Lublin']
obj4 = pd.Series(s,index=miasta)
obj4

Poznań NaN
Kraków 44323.0
Rzeszów NaN
Lublin 41988.0
dtype: float64

In [18]:
obj3+obj4

Gdańsk NaN
Kraków 88646.0
Lublin 83976.0
Poznań NaN
Rzeszów NaN
Warszawa NaN
dtype: float64

In [19]:
data = {'miasto':['Warszawa','Warszawa','Warszawa','Kraków','Kraków','Kraków'],
        'rok':[2017,2018,2019,2018,2019,2020],
        'populacja':[2.7,2.75,3.05,0.85,0.91,1.01]}

frame = pd.DataFrame(data)

In [20]:
frame

miasto 
 rok 
 populacja 
 
 
 
 
 0 
 Warszawa 
 2017 
 2.70 
 
 
 1 
 Warszawa 
 2018 
 2.75 
 
 
 2 
 Warszawa 
 2019 
 3.05 
 
 
 3 
 Kraków 
 2018 
 0.85 
 
 
 4 
 Kraków 
 2019 
 0.91 
 
 
 5 
 Kraków 
 2020 
 1.01

In [21]:
frame2 = pd.DataFrame(data,columns=['rok','miasto','populacja','waga'],index = ['jeden','dwa','trzy','cztery','pieć','sześć'])
frame2

rok 
 miasto 
 populacja 
 waga 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.70 
 NaN 
 
 
 dwa 
 2018 
 Warszawa 
 2.75 
 NaN 
 
 
 trzy 
 2019 
 Warszawa 
 3.05 
 NaN 
 
 
 cztery 
 2018 
 Kraków 
 0.85 
 NaN 
 
 
 pieć 
 2019 
 Kraków 
 0.91 
 NaN 
 
 
 sześć 
 2020 
 Kraków 
 1.01 
 NaN

In [22]:
frame2['waga']=0.12

In [23]:
frame2

rok 
 miasto 
 populacja 
 waga 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.70 
 0.12 
 
 
 dwa 
 2018 
 Warszawa 
 2.75 
 0.12 
 
 
 trzy 
 2019 
 Warszawa 
 3.05 
 0.12 
 
 
 cztery 
 2018 
 Kraków 
 0.85 
 0.12 
 
 
 pieć 
 2019 
 Kraków 
 0.91 
 0.12 
 
 
 sześć 
 2020 
 Kraków 
 1.01 
 0.12

In [24]:
import numpy as np

In [25]:
frame2['waga']=np.arange(6.)
frame2

rok 
 miasto 
 populacja 
 waga 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.70 
 0.0 
 
 
 dwa 
 2018 
 Warszawa 
 2.75 
 1.0 
 
 
 trzy 
 2019 
 Warszawa 
 3.05 
 2.0 
 
 
 cztery 
 2018 
 Kraków 
 0.85 
 3.0 
 
 
 pieć 
 2019 
 Kraków 
 0.91 
 4.0 
 
 
 sześć 
 2020 
 Kraków 
 1.01 
 5.0

In [27]:
frame2['waga'] = np.array([0.99,1.08,1.1,2,3,0.1])
frame2

rok 
 miasto 
 populacja 
 waga 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.70 
 0.99 
 
 
 dwa 
 2018 
 Warszawa 
 2.75 
 1.08 
 
 
 trzy 
 2019 
 Warszawa 
 3.05 
 1.10 
 
 
 cztery 
 2018 
 Kraków 
 0.85 
 2.00 
 
 
 pieć 
 2019 
 Kraków 
 0.91 
 3.00 
 
 
 sześć 
 2020 
 Kraków 
 1.01 
 0.10

In [32]:
daty = pd.date_range("20231210",periods=6)
daty

DatetimeIndex(['2023-12-10', '2023-12-11', '2023-12-12', '2023-12-13',
               '2023-12-14', '2023-12-15'],
              dtype='datetime64[ns]', freq='D')

In [33]:
fr = pd.DataFrame(np.random.randn(6,4),index=daty,columns=list("ABCD"))
fr

A 
 B 
 C 
 D 
 
 
 
 
 2023-12-10 
 0.128166 
 0.109471 
 0.690741 
 -1.495298 
 
 
 2023-12-11 
 0.140812 
 3.008623 
 0.811700 
 0.098192 
 
 
 2023-12-12 
 -0.542744 
 -1.059749 
 0.723882 
 0.971976 
 
 
 2023-12-13 
 1.529070 
 1.255327 
 0.037828 
 -0.604315 
 
 
 2023-12-14 
 -0.870365 
 -1.112501 
 -0.433467 
 1.715556 
 
 
 2023-12-15 
 -1.377478 
 -0.146001 
 0.201177 
 -0.216373

In [35]:
fr.head(3)

A 
 B 
 C 
 D 
 
 
 
 
 2023-12-10 
 0.128166 
 0.109471 
 0.690741 
 -1.495298 
 
 
 2023-12-11 
 0.140812 
 3.008623 
 0.811700 
 0.098192 
 
 
 2023-12-12 
 -0.542744 
 -1.059749 
 0.723882 
 0.971976

In [37]:
fr.tail(2)

A 
 B 
 C 
 D 
 
 
 
 
 2023-12-14 
 -0.870365 
 -1.112501 
 -0.433467 
 1.715556 
 
 
 2023-12-15 
 -1.377478 
 -0.146001 
 0.201177 
 -0.216373

In [38]:
nf = fr.to_numpy()
print(nf)
print(type(nf))

[[ 0.1281662   0.10947145  0.69074138 -1.49529848]
 [ 0.14081179  3.00862301  0.81170046  0.09819225]
 [-0.54274356 -1.05974862  0.72388242  0.97197563]
 [ 1.52906962  1.25532723  0.03782819 -0.60431502]
 [-0.87036481 -1.11250071 -0.43346664  1.71555572]
 [-1.37747848 -0.14600108  0.20117748 -0.21637332]]
<class 'numpy.ndarray'>


In [39]:
fr.describe()

A 
 B 
 C 
 D 
 
 
 
 
 count 
 6.000000 
 6.000000 
 6.000000 
 6.000000 
 
 
 mean 
 -0.165423 
 0.342529 
 0.338644 
 0.078289 
 
 
 std 
 1.015842 
 1.569569 
 0.490246 
 1.140935 
 
 
 min 
 -1.377478 
 -1.112501 
 -0.433467 
 -1.495298 
 
 
 25% 
 -0.788460 
 -0.831312 
 0.078666 
 -0.507330 
 
 
 50% 
 -0.207289 
 -0.018265 
 0.445959 
 -0.059091 
 
 
 75% 
 0.137650 
 0.968863 
 0.715597 
 0.753530 
 
 
 max 
 1.529070 
 3.008623 
 0.811700 
 1.715556

In [40]:
fr.T

2023-12-10 
 2023-12-11 
 2023-12-12 
 2023-12-13 
 2023-12-14 
 2023-12-15 
 
 
 
 
 A 
 0.128166 
 0.140812 
 -0.542744 
 1.529070 
 -0.870365 
 -1.377478 
 
 
 B 
 0.109471 
 3.008623 
 -1.059749 
 1.255327 
 -1.112501 
 -0.146001 
 
 
 C 
 0.690741 
 0.811700 
 0.723882 
 0.037828 
 -0.433467 
 0.201177 
 
 
 D 
 -1.495298 
 0.098192 
 0.971976 
 -0.604315 
 1.715556 
 -0.216373

In [42]:
fr.sort_index(axis=1,ascending=False)

D 
 C 
 B 
 A 
 
 
 
 
 2023-12-10 
 -1.495298 
 0.690741 
 0.109471 
 0.128166 
 
 
 2023-12-11 
 0.098192 
 0.811700 
 3.008623 
 0.140812 
 
 
 2023-12-12 
 0.971976 
 0.723882 
 -1.059749 
 -0.542744 
 
 
 2023-12-13 
 -0.604315 
 0.037828 
 1.255327 
 1.529070 
 
 
 2023-12-14 
 1.715556 
 -0.433467 
 -1.112501 
 -0.870365 
 
 
 2023-12-15 
 -0.216373 
 0.201177 
 -0.146001 
 -1.377478

In [44]:
fr.sort_values(by='B',ascending=False)

A 
 B 
 C 
 D 
 
 
 
 
 2023-12-11 
 0.140812 
 3.008623 
 0.811700 
 0.098192 
 
 
 2023-12-13 
 1.529070 
 1.255327 
 0.037828 
 -0.604315 
 
 
 2023-12-10 
 0.128166 
 0.109471 
 0.690741 
 -1.495298 
 
 
 2023-12-15 
 -1.377478 
 -0.146001 
 0.201177 
 -0.216373 
 
 
 2023-12-12 
 -0.542744 
 -1.059749 
 0.723882 
 0.971976 
 
 
 2023-12-14 
 -0.870365 
 -1.112501 
 -0.433467 
 1.715556

In [46]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Kraków','Warszawa','Lublin','Katowice'],
                    columns=['cecha_1','cecha_2','cecha_3','cecha_4'])

data

cecha_1 
 cecha_2 
 cecha_3 
 cecha_4 
 
 
 
 
 Kraków 
 0 
 1 
 2 
 3 
 
 
 Warszawa 
 4 
 5 
 6 
 7 
 
 
 Lublin 
 8 
 9 
 10 
 11 
 
 
 Katowice 
 12 
 13 
 14 
 15

In [47]:
data['cecha_2']

Kraków 1
Warszawa 5
Lublin 9
Katowice 13
Name: cecha_2, dtype: int64

In [49]:
data.loc['Kraków',['cecha_1','cecha_3']]

cecha_1 0
cecha_3 2
Name: Kraków, dtype: int64

In [50]:
data.iloc[2,[3,0,1]]

cecha_4 11
cecha_1 8
cecha_2 9
Name: Lublin, dtype: int64

In [51]:
data.iloc[[1,2],[3,1,0]]

cecha_4 
 cecha_2 
 cecha_1 
 
 
 
 
 Warszawa 
 7 
 5 
 4 
 
 
 Lublin 
 11 
 9 
 8

In [52]:
data.loc[:"Lublin","cecha_4"]

Kraków 3
Warszawa 7
Lublin 11
Name: cecha_4, dtype: int64

In [53]:
data.iloc[:,:3][data.cecha_3>10]

cecha_1 
 cecha_2 
 cecha_3 
 
 
 
 
 Katowice 
 12 
 13 
 14